### ISSUE TITLE
Posible error en la visualización de respuestas

### ISSUE THREAD

**Issue by isorna** [KairosDS/kuestions#6]
Mirar en el admin las respuestas de js2 y friki de EduardoLQ, las preguntas y respuestas salen como en columnas diferentes, algunas sin orden ni concierto.

**Comment by manufosela** [comment]
Sí. Es un daño colateral debido a un error que se producía cuando los usuarios dejaban el test a medias y continuaban en otro momento. 
Tengo que revisar para limpiar las respuestas repetidas para tomar la primera en los tests realizados.
NOTA: Esta lista de issues no es la de KuestionsMeteor ;)

**Comment by isorna** [comment]
Uff perdón... ahora lo cambio de proyecto jeje.

¬--------------------
Alvaro Isorna
